export const countries = [
  { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan',        lang: 'uz' },
  { code: 'US', flag: '🇺🇸', name: 'United States',      lang: 'en' },
  { code: 'RU', flag: '🇷🇺', name: 'Russia',             lang: 'ru' },
  { code: 'TR', flag: '🇹🇷', name: 'Türkiye',            lang: 'tr' },
  { code: 'DE', flag: '🇩🇪', name: 'Germany',            lang: 'de' },
  { code: 'FR', flag: '🇫🇷', name: 'France',             lang: 'fr' },
  { code: 'ES', flag: '🇪🇸', name: 'Spain',              lang: 'es' },
  { code: 'IT', flag: '🇮🇹', name: 'Italy',              lang: 'it' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan',              lang: 'ja' },
  { code: 'KR', flag: '🇰🇷', name: 'Korea',              lang: 'ko' },
  { code: 'CN', flag: '🇨🇳', name: 'China',              lang: 'zh' },
  { code: 'IN', flag: '🇮🇳', name: 'India',              lang: 'hi' },
  { code: 'IR', flag: '🇮🇷', name: 'Iran',               lang: 'fa' },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia',       lang: 'ar' },
  { code: 'AE', flag: '🇦🇪', name: 'UAE',                lang: 'ar' },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt',              lang: 'ar' },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal',           lang: 'pt' },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil',             lang: 'pt' },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom',     lang: 'en' },
  { code: 'CA', flag: '🇨🇦', name: 'Canada',             lang: 'en' },
  { code: 'AU', flag: '🇦🇺', name: 'Australia',          lang: 'en' },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico',             lang: 'es' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina',          lang: 'es' },
  { code: 'CO', flag: '🇨🇴', name: 'Colombia',           lang: 'es' },
  { code: 'PL', flag: '🇵🇱', name: 'Poland',             lang: 'pl' },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands',        lang: 'nl' },
  { code: 'SE', flag: '🇸🇪', name: 'Sweden',             lang: 'sv' },
  { code: 'NO', flag: '🇳🇴', name: 'Norway',             lang: 'no' },
  { code: 'FI', flag: '🇫🇮', name: 'Finland',            lang: 'fi' },
  { code: 'DK', flag: '🇩🇰', name: 'Denmark',            lang: 'da' },
  { code: 'CH', flag: '🇨🇭', name: 'Switzerland',        lang: 'de' },
  { code: 'AT', flag: '🇦🇹', name: 'Austria',            lang: 'de' },
  { code: 'BE', flag: '🇧🇪', name: 'Belgium',            lang: 'fr' },
  { code: 'GR', flag: '🇬🇷', name: 'Greece',             lang: 'el' },
  { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic',     lang: 'cs' },
  { code: 'HU', flag: '🇭🇺', name: 'Hungary',            lang: 'hu' },
  { code: 'RO', flag: '🇷🇴', name: 'Romania',            lang: 'ro' },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine',            lang: 'uk' },
  { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan',         lang: 'kk' },
  { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan',         lang: 'az' },
  { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan',         lang: 'tg' },
  { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan',       lang: 'tk' },
  { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan',         lang: 'ky' },
  { code: 'GE', flag: '🇬🇪', name: 'Georgia',            lang: 'ka' },
  { code: 'AM', flag: '🇦🇲', name: 'Armenia',            lang: 'hy' },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia',          lang: 'id' },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia',           lang: 'ms' },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand',           lang: 'th' },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam',            lang: 'vi' },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines',        lang: 'tl' },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan',           lang: 'ur' },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh',         lang: 'bn' },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria',            lang: 'en' },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa',       lang: 'en' },
  { code: 'ET', flag: '🇪🇹', name: 'Ethiopia',           lang: 'am' },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya',              lang: 'sw' },
  { code: 'GH', flag: '🇬🇭', name: 'Ghana',              lang: 'en' },
  { code: 'MA', flag: '🇲🇦', name: 'Morocco',            lang: 'ar' },
  { code: 'DZ', flag: '🇩🇿', name: 'Algeria',            lang: 'ar' },
  { code: 'TN', flag: '🇹🇳', name: 'Tunisia',            lang: 'ar' },
  { code: 'LY', flag: '🇱🇾', name: 'Libya',              lang: 'ar' },
  { code: 'IQ', flag: '🇮🇶', name: 'Iraq',               lang: 'ar' },
  { code: 'SY', flag: '🇸🇾', name: 'Syria',              lang: 'ar' },
  { code: 'JO', flag: '🇯🇴', name: 'Jordan',             lang: 'ar' },
  { code: 'LB', flag: '🇱🇧', name: 'Lebanon',            lang: 'ar' },
  { code: 'KW', flag: '🇰🇼', name: 'Kuwait',             lang: 'ar' },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar',              lang: 'ar' },
  { code: 'BH', flag: '🇧🇭', name: 'Bahrain',            lang: 'ar' },
  { code: 'OM', flag: '🇴🇲', name: 'Oman',               lang: 'ar' },
  { code: 'YE', flag: '🇾🇪', name: 'Yemen',              lang: 'ar' },
  { code: 'AF', flag: '🇦🇫', name: 'Afghanistan',        lang: 'ps' },
  { code: 'NP', flag: '🇳🇵', name: 'Nepal',              lang: 'ne' },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka',          lang: 'si' },
  { code: 'MM', flag: '🇲🇲', name: 'Myanmar',            lang: 'my' },
  { code: 'KH', flag: '🇰🇭', name: 'Cambodia',           lang: 'km' },
  { code: 'HK', flag: '🇭🇰', name: 'Hong Kong',          lang: 'zh' },
  { code: 'TW', flag: '🇹🇼', name: 'Taiwan',             lang: 'zh' },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore',          lang: 'en' },
  { code: 'IL', flag: '🇮🇱', name: 'Israel',             lang: 'he' },
  { code: 'HR', flag: '🇭🇷', name: 'Croatia',            lang: 'hr' },
  { code: 'RS', flag: '🇷🇸', name: 'Serbia',             lang: 'sr' },
  { code: 'SK', flag: '🇸🇰', name: 'Slovakia',           lang: 'sk' },
  { code: 'BG', flag: '🇧🇬', name: 'Bulgaria',           lang: 'bg' },
  { code: 'LT', flag: '🇱🇹', name: 'Lithuania',          lang: 'lt' },
  { code: 'LV', flag: '🇱🇻', name: 'Latvia',             lang: 'lv' },
  { code: 'EE', flag: '🇪🇪', name: 'Estonia',            lang: 'et' },
  { code: 'BY', flag: '🇧🇾', name: 'Belarus',            lang: 'be' },
  { code: 'MD', flag: '🇲🇩', name: 'Moldova',            lang: 'ro' },
  { code: 'AL', flag: '🇦🇱', name: 'Albania',            lang: 'sq' },
  { code: 'MK', flag: '🇲🇰', name: 'North Macedonia',    lang: 'mk' },
  { code: 'BA', flag: '🇧🇦', name: 'Bosnia',             lang: 'bs' },
  { code: 'ME', flag: '🇲🇪', name: 'Montenegro',         lang: 'cnr' },
  { code: 'SI', flag: '🇸🇮', name: 'Slovenia',           lang: 'sl' },
  { code: 'CL', flag: '🇨🇱', name: 'Chile',              lang: 'es' },
  { code: 'PE', flag: '🇵🇪', name: 'Peru',               lang: 'es' },
  { code: 'VE', flag: '🇻🇪', name: 'Venezuela',          lang: 'es' },
  { code: 'EC', flag: '🇪🇨', name: 'Ecuador',            lang: 'es' },
  { code: 'BO', flag: '🇧🇴', name: 'Bolivia',            lang: 'es' },
  { code: 'PY', flag: '🇵🇾', name: 'Paraguay',           lang: 'es' },
  { code: 'UY', flag: '🇺🇾', name: 'Uruguay',            lang: 'es' },
  { code: 'CR', flag: '🇨🇷', name: 'Costa Rica',         lang: 'es' },
  { code: 'PA', flag: '🇵🇦', name: 'Panama',             lang: 'es' },
  { code: 'GT', flag: '🇬🇹', name: 'Guatemala',          lang: 'es' },
  { code: 'HN', flag: '🇭🇳', name: 'Honduras',           lang: 'es' },
  { code: 'NI', flag: '🇳🇮', name: 'Nicaragua',          lang: 'es' },
  { code: 'DO', flag: '🇩🇴', name: 'Dominican Republic', lang: 'es' },
  { code: 'CU', flag: '🇨🇺', name: 'Cuba',               lang: 'es' },
  { code: 'MN', flag: '🇲🇳', name: 'Mongolia',           lang: 'mn' },
  { code: 'NZ', flag: '🇳🇿', name: 'New Zealand',        lang: 'en' },
  { code: 'FJ', flag: '🇫🇯', name: 'Fiji',               lang: 'en' },
  { code: 'IE', flag: '🇮🇪', name: 'Ireland',            lang: 'en' },
  { code: 'IS', flag: '🇮🇸', name: 'Iceland',            lang: 'is' },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg',         lang: 'lb' },
  { code: 'MT', flag: '🇲🇹', name: 'Malta',              lang: 'mt' },
  { code: 'CY', flag: '🇨🇾', name: 'Cyprus',             lang: 'el' },
];

export const COUNTRIES_PER_PAGE = 8;

export function getCountriesPage(page) {
  const start = page * COUNTRIES_PER_PAGE;
  return countries.slice(start, start + COUNTRIES_PER_PAGE);
}

export function getTotalPages() {
  return Math.ceil(countries.length / COUNTRIES_PER_PAGE);
}

export function findCountry(code) {
  return countries.find((c) => c.code === code);
}

export function searchCountries(query) {
  const q = query.toLowerCase();
  return countries.filter(
    (c) => c.name.toLowerCase().includes(q) || c.code.toLowerCase().includes(q),
  );
}

export default countries;
